on:
  push:
    branches:
      master
jobs:
  build:
    runs-on:
      ubuntu-18.04
    steps:
      - name: 同步当前分支
        uses: actions/checkout@v1
      - name: 配置环境
        uses: actions/setup-node@v1
        with: 
          node-version: 12.x
      - name: 发布
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm publish
        env: 
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
